# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'JsonParsing' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
 
  # Pods for JsonParsing
  pod 'Toast-Swift', '~> 5.0.1'
  pod 'Alamofire', '~> 5.5'


  target 'JsonParsingTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'JsonParsingUITests' do
    # Pods for testing
  end

end
